cmake_minimum_required(VERSION 3.24)
if(NOT EXISTS "${META_CONFIG}")
    message(FATAL_ERROR "Meta configuration is missing; run CMake configure first: ${META_CONFIG}")
endif()
file(READ "${META_CONFIG}" config)
string(JSON version GET "${config}" config_version)
if(NOT version EQUAL 1)
    message(FATAL_ERROR "Unsupported meta-config version ${version}; run CMake configure")
endif()
foreach(key python generator manifest repository_root output_dir)
    string(JSON ${key} GET "${config}" ${key})
endforeach()
if(NOT MODE STREQUAL "scan" AND NOT MODE STREQUAL "generate")
    message(FATAL_ERROR "RunMeta requires MODE=scan or MODE=generate")
endif()
execute_process(COMMAND "${python}" "${generator}" "${MODE}" --meta-config "${META_CONFIG}"
    RESULT_VARIABLE status OUTPUT_VARIABLE output ERROR_VARIABLE errors)
if(output)
    message(STATUS "${output}")
endif()
if(NOT status EQUAL 0)
    message(FATAL_ERROR "Meta ${MODE} failed (${status}):\n${errors}")
endif()
if(MODE STREQUAL "generate")
    foreach(name GeneratedReflection.h GeneratedReflection.cpp GeneratedQueries.h GeneratedQueries.cpp)
        if(NOT EXISTS "${output_dir}/${name}")
            message(FATAL_ERROR "Generator did not create required output: ${output_dir}/${name}")
        endif()
    endforeach()
    return()
endif()
if(NOT EXISTS "${manifest}")
    message(FATAL_ERROR "Successful scan did not produce ${manifest}")
endif()
file(READ "${manifest}" metadata)
string(JSON schema GET "${metadata}" schema_version)
if(NOT schema EQUAL 2)
    message(FATAL_ERROR "Build requires manifest v2, got ${schema}")
endif()
function(escape_depfile value out)
    string(REPLACE "\\" "/" value "${value}")
    string(REPLACE "$" "$$" value "${value}")
    string(REPLACE "#" "\\#" value "${value}")
    string(REPLACE " " "\\ " value "${value}")
    string(REPLACE ":" "\\:" value "${value}")
    set(${out} "${value}" PARENT_SCOPE)
endfunction()
escape_depfile("${manifest}" escaped_target)
set(dependencies "${escaped_target}:")
string(JSON dependency_count LENGTH "${metadata}" dependencies)
if(dependency_count GREATER 0)
    math(EXPR last "${dependency_count} - 1")
    foreach(index RANGE 0 ${last})
        string(JSON path GET "${metadata}" dependencies ${index} path)
        if(NOT IS_ABSOLUTE "${path}")
            set(path "${repository_root}/${path}")
        endif()
        escape_depfile("${path}" escaped_path)
        string(APPEND dependencies " ${escaped_path}")
    endforeach()
endif()
file(WRITE "${DEPFILE}" "${dependencies}\n")
