cmake_minimum_required(VERSION 3.24)
execute_process(COMMAND "${TOOL}" -p "${BUILD_ROOT}" --output "${OUTPUT}"
    --resource-dir "${RESOURCE_DIR}" --module Test --configuration Release
    --repository-root "${REPOSITORY_ROOT}" --entry-header "${ENTRY_HEADER}" "${INPUT}"
    RESULT_VARIABLE status OUTPUT_VARIABLE stdout ERROR_VARIABLE stderr)
message("${stdout}${stderr}")
if(NOT EXISTS "${OUTPUT}")
    message(FATAL_ERROR "HuaMeta did not produce the required structured report")
endif()
file(READ "${OUTPUT}" report)
string(JSON version GET "${report}" schema_version)
if(NOT version EQUAL 2)
    message(FATAL_ERROR "HuaMeta must produce manifest v2")
endif()
if(EXPECT_FAILURE)
    if(status EQUAL 0)
        message(FATAL_ERROR "Invalid C++ must fail the frontend")
    endif()
    string(JSON count LENGTH "${report}" diagnostics)
    if(count LESS 1)
        message(FATAL_ERROR "Invalid C++ needs a structured diagnostic")
    endif()
    set(located_error OFF)
    math(EXPR last "${count} - 1")
    foreach(index RANGE 0 ${last})
        string(JSON source GET "${report}" diagnostics ${index} source)
        string(JSON line GET "${report}" diagnostics ${index} line)
        string(JSON column GET "${report}" diagnostics ${index} column)
        string(JSON code GET "${report}" diagnostics ${index} code)
        if(source MATCHES "Invalid.cpp$" AND line GREATER 0 AND column GREATER 0 AND NOT code STREQUAL "")
            set(located_error ON)
        endif()
    endforeach()
    if(NOT located_error)
        message(FATAL_ERROR "Expected a stable diagnostic code and Invalid.cpp line/column")
    endif()
else()
    if(NOT status EQUAL 0)
        message(FATAL_ERROR "Valid module scan failed: ${status}")
    endif()
    string(JSON types LENGTH "${report}" types)
    string(JSON queries LENGTH "${report}" queries)
    string(JSON dependencies LENGTH "${report}" dependencies)
    if(types LESS 1 OR queries LESS 1 OR dependencies LESS 1)
        message(FATAL_ERROR "Expected real component, Query and transitive dependency records")
    endif()
    string(JSON configuration GET "${report}" configuration)
    if(NOT configuration STREQUAL "Release")
        message(FATAL_ERROR "The tool probe must record its Release configuration")
    endif()
endif()
